package:
  name: ladetector
  version: 0.9

source:
  git_url: https://github.com/bbrener1/LADetector

requirements:
  build:
    - python
    - setuptools
    - bowtie=1.2.2
    - perl=5.22.0
    - samtools
    - r

  run:
    - python

test:
  commands:
    - ladetector -diag -d -l -sn test

about:
  home:
  license:
  license_file:
